### PR TITLE
WL-3609 Change the permissions when disabling tools.

### PR DESCRIPTION
**Pull request by buckett**
When you disable a tool we change the permissions so that all roles without site.upd no longer have permission to use the tool. Todo this a tool needs to have registered it’s required functions. Because not all tools register required functions not all tools can be disabled any more.

Changing the permissions has the added benefit that it also stops users from accessing the content through web services (/direct), synoptic tools in the Home page and synoptic tools in My Workspace.

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Why do sit.upd roles still get permission to use a disabled tool?

**Comment by buckett** [comment]
site.upd are the maintainers in the site. If people don't want anyone to
use the tool then they may as well just remove it from the site.

On 7 November 2014 15:01, Nick Wilson notifications@github.com wrote:

> Why do sit.upd roles still get permission to use a disabled tool?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ox-it/wl-site-manage/pull/30#issuecomment-62156076.

## 

  Matthew Buckett, VLE Developer, IT Services, University of Oxford

**Comment by nicholaswilson100** [comment]
site.upd are the contributors to the site too I think... Is that okay?

**Comment by buckett** [comment]
Yep, if contributors have site.upd then they should be able to use the
disabled tool.

On 7 November 2014 15:07, Nick Wilson notifications@github.com wrote:

> site.upd are the contributors to the site too I think... Is that okay?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ox-it/wl-site-manage/pull/30#issuecomment-62156818.

## 

  Matthew Buckett, VLE Developer, IT Services, University of Oxford

**Comment by nicholaswilson100** [comment]
okay

**Pull request merged**
