### PR TITLE
WL-3732: Don't show suspended groups

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Linked to https://github.com/ox-it/wl-external-groups/pull/9

**Comment by buckett** [comment]
Don't organise imports on SiteAction it will never merge cleanly against SiteAction.

**Comment by nicholaswilson100** [comment]
Linked to ox-it/wl-kernel#66

**Comment by nicholaswilson100** [comment]
ok

**Comment by nicholaswilson100** [comment]
The logic here is :

**Comment by nicholaswilson100** [comment]
When we are getting the groups to show under the Participant List in Site Info, try to find a corresponding  suspended group.  We do this by going through all the other groups a site has, and seeing if there is one that matches to the one we are currently looking at but with the word 'suspended' where it has the word 'current' in its DN.

**Comment by nicholaswilson100** [comment]
Then we get the providerId of that corresponding suspended group and add it (after a comma) to the providerId of the other group., e.g., '34lj5h3245j3453h4,5ukj34h5k34h54' and this forms the 'group.id' of the group - line 4170 SiteAction.java.

Then if someone clicks Remove to remove a group, SitreAction.doRemoveGroup (line 4182) splits the string by the comma and removes each group including the suspended one.

**Comment by nicholaswilson100** [comment]
I've backed out the imports diff and rebased.

**Comment by buckett** [comment]
We should be hiding this logic behind the API in an idea world.

**Pull request merged**
